web/router.ex
defmodule Schoolit.Router do
  use Schoolit.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Schoolit.Auth, repo: Schoolit.Repo
  end

  #pipeline :api do
    #plug :accepts, ["json"]
  #end

  scope "/", Schoolit do
    pipe_through :browser # Use the default browser stack

    resources "/teachers", TeacherController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/", PageController, :index
    get "/:url_code", TimeLineController, :index do
      resources "/topic", TopicController, only: [:show]
      resources "/guest_schedule", GuestScheduleController, only: [:index]
    end

    #resources "/appointments", AppointmentController, only: [] do
      #resources "/comments", CommentController, only: [:create]
    #end
  end

  #scope "/authenticated", Schoolit.Authenticated do
    #pipe_through [:browser, :authenticate_user]
  #end

  scope "/manage", Schoolit.Manage do
    pipe_through [:browser, :authenticate_teacher]
    resources "/appointments", AppointmentController
    resources "/schedules", ScheduleController, except: [:show]
    get "/profiles", ProfileController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Schoolit do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Schoolit.LayoutView do
  use Schoolit.Web, :view
  @doc """
  Generates name for the JavaScript view we want to use
  in this combination of view/template. e.g.
  The result for the Elixir.PhoenixTemplate.AppointmentView view and index.html template will be
  AppointmentIndexView, and on the other hand, for the new.html template will be AppointmentNewView
  """
  def js_view_name(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.reverse
    |> List.insert_at(0, "view")
    |> Enum.map(&(Enum.map(String.split(&1, "_"), fn(string) -> String.capitalize(string) end)))
    |> Enum.reverse
    |> Enum.join("")
  end

  # Takes the resource name of the view module and removes the
  # the ending *_view* string.
  defp view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name
    |> String.replace("_view", "")
  end

  # Removes the extion from the template and reutrns
  # just the name.
  defp template_name(template) when is_binary(template) do
    template
    |> String.split(".")
    |> Enum.at(0)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Schoolit!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body data-js-view-name="<%= js_view_name(@conn, @view_template) %>">
    <div class="container">
      <header class="header">
        <nav class="navbar navbar-default">
          <div class="container">
            <%= if @current_teacher do %>
              <%= link to: appointment_path(@conn, :index), class: "navbar-brand" do %>
                <i class="fa fa-list" aria-hidden="true"></i>
                <%= gettext("What next?") %>
              <% end %>

              <%= link to: schedule_path(@conn, :index), class: "navbar-brand" do %>
                <i class="fa fa-table" aria-hidden="true"></i>
                <%= gettext("Timetable") %>
              <% end %>
            <% end %>
            <%= if assigns[:teacher] && !@current_teacher do %>
              <%= link to: time_line_path(@conn, :index, @teacher.url_code), class: "navbar-brand" do %>
                <i class="fa fa-list" aria-hidden="true"></i>
                <%= gettext("What next?") %>
              <% end %>

              <%= link to: guest_schedule_path(@conn, :index, url_code: @teacher.url_code), class: "navbar-brand" do %>
                <i class="fa fa-table" aria-hidden="true"></i>
                <%= gettext("Timetable") %>
              <% end %>
            <% end %>
            <ul class="nav navbar-nav">
              <li></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
              <%= if @current_teacher do %>
                <li>
                  <%= link to: profile_path(@conn, :show) do %>
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <%= @current_teacher.username %>
                  <% end %>
                </li>
                <li class="form-in-navbar">
                  <%= link to: session_path(@conn, :delete, @current_teacher), method: "delete" do %>
                    <i class="fa fa-power-off" aria-hidden="true"></i>
                    <%= gettext("Logout") %>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link "Register", to: teacher_path(@conn, :new) %>
                </li>
                <li style="margin-right: 5px;"><%= link "Log in", to: session_path(@conn, :new) %></li>
              <% end %>
            </ul>
          </div>
        </nav>
			</header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>